GET http://localhost:3000/api/jokes

###

POST http://localhost:3000/api/jokes
content-type: application/json

{
  "text": "!false — It's funny because it's true."
}

###

POST http://localhost:3000/api/jokes
content-type: application/json

{
  "text": "Why did the programmer quit his job? Because they didn't get arrays." 
}

###

GET http://localhost:3000/api/jokes/6231c79bd821c1bf61ff7

###

DELETE http://localhost:3000/api/jokes/6231efe4d821c1bf61ff7b43

###

PATCH http://localhost:3000/api/jokes/6231f005d821c1bf61ff7b47
content-type: application/json

{
  "text": "Why did the programmer quit his job? Because they didn't get arrays." 
}